{"name": "test_login_nonexistent_user", "status": "passed", "description": "Проверка:попытка авторизации под несуществующим пользователем возвращает ошибку", "start": 1722980606460, "stop": 1722980606685, "uuid": "d3163ad3-b4f8-4e60-a4ba-99d851628c9d", "historyId": "723ce2b188a8b83c6197faf747af910a", "testCaseId": "723ce2b188a8b83c6197faf747af910a", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_nonexistent_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "LAPTOP-74V5TFPG"}, {"name": "thread", "value": "4752-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}