{"name": "test_login_nonexistent_user", "status": "passed", "description": "Проверка:попытка авторизации под несуществующим пользователем возвращает ошибку", "start": 1722979298331, "stop": 1722979298496, "uuid": "5f92d9a2-d2ea-4631-a3f3-b921b2ab3086", "historyId": "723ce2b188a8b83c6197faf747af910a", "testCaseId": "723ce2b188a8b83c6197faf747af910a", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_nonexistent_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "LAPTOP-74V5TFPG"}, {"name": "thread", "value": "17876-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}