{"name": "test_login_nonexistent_user", "status": "passed", "description": "Проверка:попытка авторизации под несуществующим пользователем возвращает ошибку", "start": 1722979609223, "stop": 1722979609380, "uuid": "79ef9e69-8e02-4422-b97f-89b38cee917c", "historyId": "723ce2b188a8b83c6197faf747af910a", "testCaseId": "723ce2b188a8b83c6197faf747af910a", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_nonexistent_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "LAPTOP-74V5TFPG"}, {"name": "thread", "value": "14364-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}